name: complete flux

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chckout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Setup Chrome Driver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 127.0.6533.119

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run RobotFramework Tests
        run: cd tests && python run_tests.py

      - name: Archive Robot Framework logs
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: ./logs
